language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

# faster builds on new travis setup not using sudo
sudo: false

services:
  - redis-server

install:
  - travis_retry phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --dev --prefer-dist --no-interaction

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/codecept run --steps functional -d
