language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - PREFER_LOWEST="--prefer-lowest --prefer-stable"
    - PREFER_LOWEST=""

# faster builds on new travis setup not using sudo
sudo: false

services:
  - redis-server

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - php --version
  - composer update $PREFER_LOWEST

script:
  - composer ci
  - vendor/bin/codecept run --steps functional -d
